# Generated by Django 5.1.7 on 2025-05-30 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('HOME', 'Casa'), ('WORK', 'Trabalho'), ('OTHER', 'Outro')], default='HOME', help_text='Tipo de endereço (Casa, Trabalho, Outro)', max_length=10)),
                ('address_line1', models.CharField(help_text='Primeira linha do endereço (rua, número)', max_length=100)),
                ('address_line2', models.CharField(blank=True, default='', help_text='Segunda linha do endereço (complemento)', max_length=100)),
                ('city', models.CharField(help_text='Cidade', max_length=50)),
                ('state', models.CharField(help_text='Estado', max_length=50)),
                ('country', models.CharField(default='Brasil', help_text='País', max_length=50)),
                ('postal_code', models.CharField(help_text='CEP', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, help_text='Latitude da localização', max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, help_text='Longitude da localização', max_digits=18, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Indica se este é o endereço padrão do usuário')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do endereço')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização do endereço')),
                ('user', models.ForeignKey(help_text='Usuário proprietário deste endereço', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
