# Generated by Django 5.0.2 on 2024-05-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_2',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
