# Generated by Django 5.1.7 on 2025-05-30 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Nome da categoria (ex: Entradas, Sobremesas)', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='Slug para URL (gerado a partir do nome da categoria)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição opcional da categoria', max_length=250)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação da categoria')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização')),
                ('vendor', models.ForeignKey(help_text='Restaurante ao qual esta categoria pertence', on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_title', models.CharField(help_text='Nome do item de comida', max_length=50)),
                ('slug', models.SlugField(help_text='Slug para URL (gerado a partir do nome do item)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição do item de comida', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço do item', max_digits=10)),
                ('image', models.ImageField(help_text='Imagem do item de comida', upload_to='foodimages')),
                ('is_available', models.BooleanField(default=True, help_text='Indica se o item está disponível para pedido')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora de criação do item')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização')),
                ('category', models.ForeignKey(help_text='Categoria à qual este item pertence', on_delete=django.db.models.deletion.CASCADE, related_name='fooditems', to='menu.category')),
                ('vendor', models.ForeignKey(help_text='Restaurante ao qual este item pertence', on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'item de comida',
                'verbose_name_plural': 'itens de comida',
                'ordering': ('created_at',),
            },
        ),
    ]
