# Generated by Django 5.0.2 on 2024-05-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
